---
# RuntimeClass for kata-qemu (the default and most stable Kata hypervisor)
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata
handler: kata
---
# Additional RuntimeClass specifically naming kata-qemu
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata-qemu
handler: kata-qemu
---
# RuntimeClass for kata-clh (Cloud Hypervisor - lighter weight alternative)
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata-clh
handler: kata-clh
